language: node_js
sudo: false
node_js:
- '9'

branches:
  only:
  - develop
  - sandbox

cache:
  directories:
    - "node_modules"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: tf-sand-server
  on:
    repo: frontend-park-mail-ru/2018_1_tarados-feroces
    branch: sandbox
  skip_cleanup: true

script:
  - npm run eslint
  - npm run webpack-prod
