language: node_js
sudo: false
node_js:
- '9'

branches:
  only:
  - develop
  - feature-add-lint-to-travis
  - feature-parse-html

cache:
  directories:
    - "node_modules"

deploy:
  provider: heroku
  api_key:
    secure: $HEROCU_KEY
  app: tf-test-server
  on:
    repo: frontend-park-mail-ru/2018_1_tarados-feroces
    branch: feature-parse-html
  skip_cleanup: true

before_script:
  - npm install

script:
  - npm run eslint
